-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 11:05:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema dbTandarts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbTandarts
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `dbTandarts` ;
USE `dbTandarts` ;

-- -----------------------------------------------------
-- Table `dbTandarts`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(225) NULL,
  `Wachtwoord` VARCHAR(225) NULL,
  `Usertype` ENUM("Patiënt", "Tandarts", "Admin") NULL DEFAULT 'Patiënt',
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTandarts`.`Patiënt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Patiënt` (
  `PatiëntID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(225) NULL,
  `Geboortedatum` VARCHAR(225) NULL,
  `Telefoonnummer` VARCHAR(225) NULL,
  `adres` VARCHAR(225) NULL,
  PRIMARY KEY (`PatiëntID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTandarts`.`Tandarts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Tandarts` (
  `tandartsID` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(225) NULL,
  `Geboortedarum` VARCHAR(225) NULL,
  `Telefoonnummer` VARCHAR(12) NULL,
  `Adres` VARCHAR(225) NULL,
  `Beoordeling` FLOAT NULL,
  `Specialisaties` VARCHAR(225) NULL,
  `Beschrijving` VARCHAR(225) NULL,
  PRIMARY KEY (`tandartsID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTandarts`.`Afspraken`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Afspraken` (
  `afspraakID` INT NOT NULL AUTO_INCREMENT,
  `DatumTijd` DATETIME(20) NULL,
  `Beschrijving` VARCHAR(225) NULL,
  `Users_userID` INT NOT NULL,
  PRIMARY KEY (`afspraakID`),
  INDEX `fk_Afspraken_Users_idx` (`Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Afspraken_Users`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `dbTandarts`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTandarts`.`Behandelingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Behandelingen` (
  `BehandelingenID` INT NOT NULL AUTO_INCREMENT,
  `Users_userID` INT NOT NULL,
  `Beschrijving` VARCHAR(225) NULL,
  PRIMARY KEY (`BehandelingenID`),
  INDEX `fk_Behandelingen_Users1_idx` (`Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Behandelingen_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `dbTandarts`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbTandarts`.`Verzekeringen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbTandarts`.`Verzekeringen` (
  `VerzekeringenID` INT NOT NULL AUTO_INCREMENT,
  `Users_userID` INT NOT NULL,
  `Beschrijving` VARCHAR(225) NULL,
  PRIMARY KEY (`VerzekeringenID`),
  INDEX `fk_Verzekeringen_Users1_idx` (`Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Verzekeringen_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `dbTandarts`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)